# Generated by Django 4.1.3 on 2023-01-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(default='exxtt', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
